com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:124)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:135)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.getValue(AbstractPullReader.java:197)
	at com.intellij.database.model.serialization.FixHierarchicalStreamReader.getValue(FixHierarchicalStream.kt)
	at com.intellij.database.model.serialization.ModelImporter.deserializeObject(ModelImporter.java:177)
	at com.intellij.database.model.serialization.ModelImporter.deserializeModel(ModelImporter.java:121)
	at com.intellij.database.model.serialization.ModelSerializerKt.deserialize(ModelSerializer.kt:25)
	at com.intellij.database.model.serialization.ModelSerializerKt.deserialize(ModelSerializer.kt:15)
	at com.intellij.database.dataSource.DataSourceStorage.readModel(DataSourceStorage.java:768)
	at com.intellij.database.dataSource.DataSourceStorage.readModel(DataSourceStorage.java:756)
	at com.intellij.database.dataSource.DataSourceStorage.loadModels(DataSourceStorage.java:561)
	at com.intellij.database.dataSource.DataSourceStorage.readStateHeavy(DataSourceStorage.java:441)
	at com.intellij.database.dataSource.DataSourceStorage.access$000(DataSourceStorage.java:92)
	at com.intellij.database.dataSource.DataSourceStorage$2.run(DataSourceStorage.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.xmlpull.v1.XmlPullParserException: end tag name </Dat> must match start tag name <DataType> from line 108 (position: TEXT seen ...<DataType>integer|0s</Dat$... @108:33) 
	at org.xmlpull.mxp1.MXParser.parseEndTag(MXParser.java:1689)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1131)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	... 31 more
